# generated by datamodel-codegen:
#   filename:  schema_db.json
#   timestamp: 2022-04-19T08:23:29+00:00

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field


class _Id(BaseModel):
    _oid: str = Field(..., alias='$oid')


class CreatedAt(BaseModel):
    _date: str = Field(..., alias='$date')


class UpdatedAt(BaseModel):
    _date: str = Field(..., alias='$date')


class User(BaseModel):
    email: str
    affiliation: str


class Project(BaseModel):
    name: str
    description: str
    label: str


class Parameter(BaseModel):
    name: str
    type: str
    value: float


class SwAgent(BaseModel):
    name: str
    version: str


class Calculation(BaseModel):
    method: str
    swAgent: SwAgent


class SwAgent1(BaseModel):
    name: str
    version: str


class Experiment(BaseModel):
    method: str
    swAgent: SwAgent1


class ChemicalCompositionItem(BaseModel):
    element: str
    percentage: str


class Lattice(BaseModel):
    a: str
    b: str
    c: str
    alpha: str
    beta: str
    gamma: str


class Input(BaseModel):
    lattice: Lattice
    sites: str
    species: str


class Lattice1(BaseModel):
    a: str
    b: str
    c: str
    alpha: str
    beta: str
    gamma: str


class Output(BaseModel):
    lattice: Lattice1
    sites: str
    species: str


class Material(BaseModel):
    formula: str
    elements: List[Union[str, str]]
    chemicalComposition: List[ChemicalCompositionItem]
    input: Input
    output: Output


class Axis(BaseModel):
    labelX: str
    labelY: str


class Units(BaseModel):
    x: str
    y: str


class CreatedAt1(BaseModel):
    _date: str = Field(..., alias='$date')


class UpdatedAt1(BaseModel):
    _date: str = Field(..., alias='$date')


class File(BaseModel):
    hash: str
    extention: str
    size: str
    createdAt: CreatedAt1
    updatedAt: UpdatedAt1


class Property(BaseModel):
    name: str
    type: str
    axis: Axis
    value: float
    units: Units
    file: File
    isCalculated: bool
    isPhysical: bool


class Process(BaseModel):
    isExperiment: bool
    isSimulation: bool
    parameters: List[Parameter]
    calculation: Calculation
    experiment: Experiment
    material: Material
    properties: List[Property]
    iemapID: str


class CreatedAt2(BaseModel):
    _date: str = Field(..., alias='$date')


class UpdatedAt2(BaseModel):
    _date: str = Field(..., alias='$date')


class Date(BaseModel):
    _date: str = Field(..., alias='$date')


class Publication(BaseModel):
    name: str
    date: Date
    url: str


class File1(BaseModel):
    hash: str
    description: str
    name: str
    extention: str
    type: str
    isProcessed: bool
    size: str
    createdAt: CreatedAt2
    updatedAt: UpdatedAt2
    publication: Publication


class Model(BaseModel):
    _id: _Id
    createdAt: CreatedAt
    updatedAt: UpdatedAt
    user: User
    project: Project
    process: Process
    files: List[File1]
    _v: str
    projectWP: str
