# generated by datamodel-codegen:
#   filename:  schema_db.json
#   timestamp: 2022-04-19T08:23:29+00:00

from __future__ import annotations
from datetime import datetime
from bson.objectid import ObjectId

from typing import List, Union, Optional

from pydantic import BaseModel, Field, validator
from pydantic.class_validators import root_validator


class ObjectIdStr(str):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        try:
            return ObjectId(v)
        except Exception:
            raise ValueError(f"{v} is not a valid ObjectId")
        return str(v)


class UpdatedAt(BaseModel):
    _date: Optional[str] = datetime.now().utcnow()


class User(BaseModel):
    email: str
    affiliation: str


class Project(BaseModel):
    name: str
    description: str
    label: str


class Parameter(BaseModel):
    name: str
    type: str
    value: float


class SwAgent(BaseModel):
    name: str
    version: str


class Calculation(BaseModel):
    method: str
    swAgent: SwAgent


class SwAgent1(BaseModel):
    name: str
    version: str


class Experiment(BaseModel):
    method: str
    swAgent: SwAgent1


class ChemicalCompositionItem(BaseModel):
    element: str
    percentage: str


class Lattice(BaseModel):
    a: str
    b: str
    c: str
    alpha: str
    beta: str
    gamma: str


class Input(BaseModel):
    lattice: Lattice
    sites: str
    species: str


class Lattice1(BaseModel):
    a: str
    b: str
    c: str
    alpha: str
    beta: str
    gamma: str


class Output(BaseModel):
    lattice: Lattice1
    sites: str
    species: str


class Material(BaseModel):
    formula: str
    elements: List[Union[str, str]]
    chemicalComposition: List[ChemicalCompositionItem]
    input: Input
    output: Output


class Axis(BaseModel):
    labelX: str
    labelY: str


class Units(BaseModel):
    x: str
    y: str


class CreatedAt1(BaseModel):
    _date: str = Field(alias="$date")


class UpdatedAt1(BaseModel):
    _date: str = Field(alias="$date")


class File(BaseModel):
    hash: str
    extention: str
    size: str
    createdAt: CreatedAt1
    updatedAt: UpdatedAt1


class Property(BaseModel):
    name: str
    type: str
    axis: Axis
    value: float
    units: Units
    file: File
    isCalculated: bool
    isPhysical: bool


class Process(BaseModel):
    isExperiment: bool
    isSimulation: bool
    parameters: List[Parameter]
    calculation: Calculation
    experiment: Experiment
    material: Material
    properties: List[Property]
    iemapID: str


class CreatedAt2(BaseModel):
    _date: str = Field(..., alias="$date")


class UpdatedAt2(BaseModel):
    _date: str = Field(..., alias="$date")


class Date(BaseModel):
    _date: str = Field(..., alias="$date")


class Publication(BaseModel):
    name: str
    date: Date
    url: str


class File1(BaseModel):
    hash: str
    description: str
    name: str
    extention: str
    type: str
    isProcessed: bool
    size: str
    createdAt: CreatedAt2
    updatedAt: UpdatedAt2
    publication: Publication


class timestamp(BaseModel):
    date: Optional[datetime] = None

    class Config:
        validate_assignment = True

    @validator("date", pre=True, always=True)
    def set_name(cls, date):
        return date or datetime.now().utcnow()


def validate_datetime(cls, values):
    """
    Reusable validator for pydantic models
    """
    return values or datetime.now().utcnow()


class newProject(BaseModel):

    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None
    user: User
    project: Project
    process: Process
    # files: List[File1]
    _v: str
    # projectWP: str
    class Config:
        validate_assignment = True

    @validator("createdAt", pre=True, always=True)
    def set_createdAt(cls, createdAt):
        return createdAt or datetime.now().utcnow()

    @validator("updatedAt", pre=True, always=True)
    def set_updatedAt(cls, updatedAt):
        return updatedAt or datetime.now().utcnow()


# https://stackoverflow.com/questions/63616798/pydantic-how-to-pass-the-default-value-to-a-variable-if-none-was-passed
# https://github.com/samuelcolvin/pydantic/issues/1593
